### ISSUE TITLE
Repo structure definition

### ISSUE THREAD

**Issue by anwielts** [Glassmasters/BirdCLEF_Glassmasters#1]
@MarionHinkel @Flippchen We have to decide on a repo structure. Maybe we can follow the steps outlined [here ](https://towardsdatascience.com/how-to-structure-a-data-science-project-for-readability-and-transparency-360c6716800?gi=9ab6667799eb). This leverages [cookiecutter](https://github.com/cookiecutter/cookiecutter)

**Comment by anwielts** [comment]
@Flippchen Do we want to merge the PR to get the project started? I mean we can delete stuff we do not need from this template down the line

**Comment by Flippchen** [comment]
Sounds good. I will merge it into dev branch.
