### ISSUE TITLE
ClearML stuff (start)

### ISSUE THREAD

**Issue by anwielts** [Glassmasters/BirdCLEF_Glassmasters#4]
Hi, @Flippchen and @MarionHinkel: I would need your E-mail addresses so that I can invite you to my ClearML workspace. I will post stuff to get started with ClearML in this issue

**Comment by Flippchen** [comment]
I sent them to you in teams

**Comment by anwielts** [comment]
When you have access to the ClearML instance you can follow these two posts to get up and running:
1. https://clear.ml/docs/latest/docs/getting_started/ds/ds_first_steps/
2. https://clear.ml/docs/latest/docs/getting_started/ds/ds_second_steps/

Nice video tutorial: https://www.youtube.com/watch?v=quSGXvuK1IM

**Comment by anwielts** [comment]
Small example on how to start with ClearML (it is really easy):
`import numpy as np
from sklearn.linear_model import LinearRegression
try:
    import joblib
except ImportError:
    from sklearn.externals import joblib
	
from clearml import Task

task = Task.init(project_name='<Our project>', task_name='New experiment')

params_dictionary = {'test_param': 123, 'score': -1}

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

task.upload_artifact(name='features', artifact_object=X)
task.upload_artifact(name='targets', artifact_object=y)

reg = LinearRegression().fit(X, y)
joblib.dump(reg, 'model.pkl', compress=True)
params_dictionary['score'] = reg.score(X, y)

task.connect(params_dictionary)
`

This script:
- Tracks the code and its configuration to our project as a New experiment
- Uploads the dataset via the .upload_artifact function
- Automagically when a model is stored locally also uploads the model to our project

**Comment by Flippchen** [comment]
You can now add me on clearml.
Just wanted to note that in any case only submissions from notebooks are allowed, so it must run on kaggle in under 12h 😅

**Comment by anwielts** [comment]
@MarionHinkel @Flippchen ClearML invitations are out. For the time being I would use ClearML solely for tracking experiments, preprocessing changes and dataset changes.
P. S.: ClearML functionality can also be used out of notebooks

**Comment by Flippchen** [comment]
Nice. Got it connected

**Comment by anwielts** [comment]
Close this issue for now, when we have further CLearML related stuff to do we can open new specialised issues
